version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    restart: on-failure:10
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      - tig
      # - tick      


  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /var/log:/var/log:ro
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - tig
      # - tick

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - ./grafana/env.grafana
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - tig




networks:
  tig:
    driver: bridge
  # tick:
  #   driver: bridge

volumes:
  grafana-storage:
  influxdb-storage: